name: "Release to Hoster"

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    name: "Build/Deploy Process"
    environment: Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOSTER_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.HOSTER_SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "README.md"
          target: "/home/snamichist/build/"
