name: "Release to Hoster"

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    name: "Build/Deploy Process"
    environment: Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Start Build Process
        run: |
          npm i
          npm run build
          ls -la build/
          
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/
          retention-days: 5
