name: "Release to Hoster"

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    name: "Build/Deploy Process"
    environment: Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Start Build Process
        run: |
          npm i
          CI=false
          echo $CI
          npm run build
          
      - name: Copy File to Hoster Folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTER_SERVER }}
          username: ${{ secrets.HOSTER_SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "build/*"
          target: "/home/snamichist/public_html" 
          
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/
          retention-days: 5
